# Custom Language File for Launcher Customizer

[ejs.app]
title = "TAG Server"

[ejs.landing]
mediaGitHubURL = "https://github.com/910TAGSERVER/TAG-Server"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/D942Myqm"

[ejs.settings]
sourceGithubLink = "https://github.com/910TAGSERVER/TAG-Server"
supportLink = "https://github.com/910TAGSERVER/TAG-Server/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO TAG Server"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
